[package]
name = "d3d9_device_grabber"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["windef", "minwindef", "winuser", "processthreadsapi", "d3d9", "d3d9types"] }
thiserror = "1.0"
